package com.sparta.filmfly.domain.movie.entity;

import lombok.Getter;

@Getter
public enum LanguagesEnum{
    AF_ZA("af-ZA"), // 아프리칸스어 (남아프리카 공화국)
    AM_ET("am-ET"), // 암하라어 (에티오피아)
    AR_AE("ar-AE"), // 아랍어 (아랍에미리트)
    AR_BH("ar-BH"), // 아랍어 (바레인)
    AR_DZ("ar-DZ"), // 아랍어 (알제리)
    AR_EG("ar-EG"), // 아랍어 (이집트)
    AR_IQ("ar-IQ"), // 아랍어 (이라크)
    AR_JO("ar-JO"), // 아랍어 (요르단)
    AR_KW("ar-KW"), // 아랍어 (쿠웨이트)
    AR_LB("ar-LB"), // 아랍어 (레바논)
    AR_LY("ar-LY"), // 아랍어 (리비아)
    AR_MA("ar-MA"), // 아랍어 (모로코)
    AR_OM("ar-OM"), // 아랍어 (오만)
    AR_QA("ar-QA"), // 아랍어 (카타르)
    AR_SA("ar-SA"), // 아랍어 (사우디아라비아)
    AR_SY("ar-SY"), // 아랍어 (시리아)
    AR_TN("ar-TN"), // 아랍어 (튀니지)
    AR_YE("ar-YE"), // 아랍어 (예멘)
    BE_BY("be-BY"), // 벨라루스어 (벨라루스)
    BG_BG("bg-BG"), // 불가리아어 (불가리아)
    BN_BD("bn-BD"), // 벵골어 (방글라데시)
    BN_IN("bn-IN"), // 벵골어 (인도)
    CA_ES("ca-ES"), // 카탈루냐어 (스페인)
    CS_CZ("cs-CZ"), // 체코어 (체코 공화국)
    DA_DK("da-DK"), // 덴마크어 (덴마크)
    DE_AT("de-AT"), // 독일어 (오스트리아)
    DE_CH("de-CH"), // 독일어 (스위스)
    DE_DE("de-DE"), // 독일어 (독일)
    EL_GR("el-GR"), // 그리스어 (그리스)
    EN_AU("en-AU"), // 영어 (호주)
    EN_CA("en-CA"), // 영어 (캐나다)
    EN_GB("en-GB"), // 영어 (영국)
    EN_IE("en-IE"), // 영어 (아일랜드)
    EN_IN("en-IN"), // 영어 (인도)
    EN_NZ("en-NZ"), // 영어 (뉴질랜드)
    EN_US("en-US"), // 영어 (미국)
    ES_AR("es-AR"), // 스페인어 (아르헨티나)
    ES_BO("es-BO"), // 스페인어 (볼리비아)
    ES_CL("es-CL"), // 스페인어 (칠레)
    ES_CO("es-CO"), // 스페인어 (콜롬비아)
    ES_CR("es-CR"), // 스페인어 (코스타리카)
    ES_DO("es-DO"), // 스페인어 (도미니카 공화국)
    ES_EC("es-EC"), // 스페인어 (에콰도르)
    ES_ES("es-ES"), // 스페인어 (스페인)
    ES_GT("es-GT"), // 스페인어 (과테말라)
    ES_HN("es-HN"), // 스페인어 (온두라스)
    ES_MX("es-MX"), // 스페인어 (멕시코)
    ES_NI("es-NI"), // 스페인어 (니카라과)
    ES_PA("es-PA"), // 스페인어 (파나마)
    ES_PE("es-PE"), // 스페인어 (페루)
    ES_PR("es-PR"), // 스페인어 (푸에르토리코)
    ES_PY("es-PY"), // 스페인어 (파라과이)
    ES_SV("es-SV"), // 스페인어 (엘살바도르)
    ES_US("es-US"), // 스페인어 (미국)
    ES_UY("es-UY"), // 스페인어 (우루과이)
    ES_VE("es-VE"), // 스페인어 (베네수엘라)
    ET_EE("et-EE"), // 에스토니아어 (에스토니아)
    FA_IR("fa-IR"), // 페르시아어 (이란)
    FI_FI("fi-FI"), // 핀란드어 (핀란드)
    FR_BE("fr-BE"), // 프랑스어 (벨기에)
    FR_CA("fr-CA"), // 프랑스어 (캐나다)
    FR_CH("fr-CH"), // 프랑스어 (스위스)
    FR_FR("fr-FR"), // 프랑스어 (프랑스)
    HE_IL("he-IL"), // 히브리어 (이스라엘)
    HI_IN("hi-IN"), // 힌디어 (인도)
    HR_HR("hr-HR"), // 크로아티아어 (크로아티아)
    HU_HU("hu-HU"), // 헝가리어 (헝가리)
    ID_ID("id-ID"), // 인도네시아어 (인도네시아)
    IT_IT("it-IT"), // 이탈리아어 (이탈리아)
    JA_JP("ja-JP"), // 일본어 (일본)
    KO_KR("ko-KR"), // 한국어 (대한민국)
    LT_LT("lt-LT"), // 리투아니아어 (리투아니아)
    LV_LV("lv-LV"), // 라트비아어 (라트비아)
    MS_MY("ms-MY"), // 말레이어 (말레이시아)
    NL_BE("nl-BE"), // 네덜란드어 (벨기에)
    NL_NL("nl-NL"), // 네덜란드어 (네덜란드)
    NO_NO("no-NO"), // 노르웨이어 (노르웨이)
    PL_PL("pl-PL"), // 폴란드어 (폴란드)
    PT_BR("pt-BR"), // 포르투갈어 (브라질)
    PT_PT("pt-PT"), // 포르투갈어 (포르투갈)
    RO_RO("ro-RO"), // 루마니아어 (루마니아)
    RU_RU("ru-RU"), // 러시아어 (러시아)
    SK_SK("sk-SK"), // 슬로바키아어 (슬로바키아)
    SL_SI("sl-SI"), // 슬로베니아어 (슬로베니아)
    SR_RS("sr-RS"), // 세르비아어 (세르비아)
    SV_SE("sv-SE"), // 스웨덴어 (스웨덴)
    TH_TH("th-TH"), // 태국어 (태국)
    TR_TR("tr-TR"), // 터키어 (터키)
    UK_UA("uk-UA"), // 우크라이나어 (우크라이나)
    VI_VN("vi-VN"), // 베트남어 (베트남)
    ZH_CN("zh-CN"), // 중국어 (중국)
    ZH_HK("zh-HK"), // 중국어 (홍콩)
    ZH_TW("zh-TW"); // 중국어 (대만)

    private final String value;

    LanguagesEnum(String value) {
        this.value = value;
    }
}
