package com.sparta.filmfly.domain.movie.entity;

import lombok.Getter;

@Getter
public enum OriginLanguageEnum {
    XX("xx", "No Language", "No Language"),
    AA("aa", "Afar", ""),
    AF("af", "Afrikaans", "Afrikaans"),
    AK("ak", "Akan", ""),
    AN("an", "Aragonese", ""),
    AS("as", "Assamese", ""),
    AV("av", "Avaric", ""),
    AE("ae", "Avestan", ""),
    AY("ay", "Aymara", ""),
    AZ("az", "Azerbaijani", "Azərbaycan"),
    BA("ba", "Bashkir", ""),
    BM("bm", "Bambara", "Bamanankan"),
    BI("bi", "Bislama", ""),
    BO("bo", "Tibetan", ""),
    BR("br", "Breton", ""),
    CA("ca", "Catalan", "Català"),
    CS("cs", "Czech", "Český"),
    CE("ce", "Chechen", ""),
    CU("cu", "Slavic", ""),
    CV("cv", "Chuvash", ""),
    KW("kw", "Cornish", ""),
    CO("co", "Corsican", ""),
    CR("cr", "Cree", ""),
    CY("cy", "Welsh", "Cymraeg"),
    DA("da", "Danish", "Dansk"),
    DE("de", "German", "Deutsch"),
    DV("dv", "Divehi", ""),
    DZ("dz", "Dzongkha", ""),
    EO("eo", "Esperanto", "Esperanto"),
    ET("et", "Estonian", "Eesti"),
    EU("eu", "Basque", "euskera"),
    FO("fo", "Faroese", ""),
    FJ("fj", "Fijian", ""),
    FI("fi", "Finnish", "suomi"),
    FR("fr", "French", "Français"),
    FY("fy", "Frisian", ""),
    FF("ff", "Fulah", "Fulfulde"),
    GD("gd", "Gaelic", ""),
    GA("ga", "Irish", "Gaeilge"),
    GL("gl", "Galician", "Galego"),
    GV("gv", "Manx", ""),
    GN("gn", "Guarani", ""),
    GU("gu", "Gujarati", ""),
    HT("ht", "Haitian; Haitian Creole", ""),
    HA("ha", "Hausa", "Hausa"),
    SH("sh", "Serbo-Croatian", ""),
    HZ("hz", "Herero", ""),
    HO("ho", "Hiri Motu", ""),
    HR("hr", "Croatian", "Hrvatski"),
    HU("hu", "Hungarian", "Magyar"),
    IG("ig", "Igbo", ""),
    IO("io", "Ido", ""),
    II("ii", "Yi", ""),
    IU("iu", "Inuktitut", ""),
    IE("ie", "Interlingue", ""),
    IA("ia", "Interlingua", ""),
    ID("id", "Indonesian", "Bahasa indonesia"),
    IK("ik", "Inupiaq", ""),
    IS("is", "Icelandic", "Íslenska"),
    IT("it", "Italian", "Italiano"),
    JV("jv", "Javanese", ""),
    JA("ja", "Japanese", "日本語"),
    KL("kl", "Kalaallisut", ""),
    KN("kn", "Kannada", "ಕನ್ನಡ"),
    KS("ks", "Kashmiri", ""),
    KR("kr", "Kanuri", ""),
    KK("kk", "Kazakh", "қазақ"),
    KM("km", "Khmer", ""),
    KI("ki", "Kikuyu", ""),
    RW("rw", "Kinyarwanda", "Kinyarwanda"),
    KY("ky", "Kirghiz", "Кыргызча"),
    KV("kv", "Komi", ""),
    KG("kg", "Kongo", ""),
    KO("ko", "Korean", "한국어/조선말"),
    KJ("kj", "Kuanyama", ""),
    KU("ku", "Kurdish", ""),
    LO("lo", "Lao", ""),
    LA("la", "Latin", "Latin"),
    LV("lv", "Latvian", "Latviešu"),
    LI("li", "Limburgish", ""),
    LN("ln", "Lingala", ""),
    LT("lt", "Lithuanian", "Lietuvių"),
    LB("lb", "Letzeburgesch", ""),
    LU("lu", "Luba-Katanga", ""),
    LG("lg", "Ganda", ""),
    MH("mh", "Marshall", ""),
    ML("ml", "Malayalam", ""),
    MR("mr", "Marathi", ""),
    MG("mg", "Malagasy", ""),
    MT("mt", "Maltese", "Malti"),
    MO("mo", "Moldavian", ""),
    MN("mn", "Mongolian", ""),
    MI("mi", "Maori", ""),
    MS("ms", "Malay", "Bahasa melayu"),
    MY("my", "Burmese", ""),
    NA("na", "Nauru", ""),
    NV("nv", "Navajo", ""),
    NR("nr", "Ndebele", ""),
    ND("nd", "Ndebele", ""),
    NG("ng", "Ndonga", ""),
    NE("ne", "Nepali", ""),
    NL("nl", "Dutch", "Nederlands"),
    NN("nn", "Norwegian Nynorsk", ""),
    NB("nb", "Norwegian Bokmål", "Bokmål"),
    NO("no", "Norwegian", "Norsk"),
    NY("ny", "Chichewa; Nyanja", ""),
    OC("oc", "Occitan", ""),
    OJ("oj", "Ojibwa", ""),
    OR("or", "Oriya", ""),
    OM("om", "Oromo", ""),
    OS("os", "Ossetian; Ossetic", ""),
    PI("pi", "Pali", ""),
    PL("pl", "Polish", "Polski"),
    PT("pt", "Portuguese", "Português"),
    QU("qu", "Quechua", ""),
    RM("rm", "Raeto-Romance", ""),
    RO("ro", "Romanian", "Română"),
    RN("rn", "Rundi", "Kirundi"),
    RU("ru", "Russian", "Pусский"),
    SG("sg", "Sango", ""),
    SA("sa", "Sanskrit", ""),
    SI("si", "Sinhalese", "සිංහල"),
    SK("sk", "Slovak", "Slovenčina"),
    SL("sl", "Slovenian", "Slovenščina"),
    SE("se", "Northern Sami", ""),
    SM("sm", "Samoan", ""),
    SN("sn", "Shona", ""),
    SD("sd", "Sindhi", ""),
    SO("so", "Somali", "Somali"),
    ST("st", "Sotho", ""),
    ES("es", "Spanish", "Español"),
    SQ("sq", "Albanian", "shqip"),
    SC("sc", "Sardinian", ""),
    SR("sr", "Serbian", "Srpski"),
    SS("ss", "Swati", ""),
    SU("su", "Sundanese", ""),
    SW("sw", "Swahili", "Kiswahili"),
    SV("sv", "Swedish", "svenska"),
    TY("ty", "Tahitian", ""),
    TA("ta", "Tamil", "தமிழ்"),
    TT("tt", "Tatar", ""),
    TE("te", "Telugu", "తెలుగు"),
    TG("tg", "Tajik", ""),
    TL("tl", "Tagalog", ""),
    TH("th", "Thai", "ภาษาไทย"),
    TI("ti", "Tigrinya", ""),
    TO("to", "Tonga", ""),
    TN("tn", "Tswana", ""),
    TS("ts", "Tsonga", ""),
    TK("tk", "Turkmen", ""),
    TR("tr", "Turkish", "Türkçe"),
    TW("tw", "Twi", ""),
    UG("ug", "Uighur", ""),
    UK("uk", "Ukrainian", "Український"),
    UR("ur", "Urdu", "اردو"),
    UZ("uz", "Uzbek", "ozbek"),
    VE("ve", "Venda", ""),
    VI("vi", "Vietnamese", "Tiếng Việt"),
    VO("vo", "Volapük", ""),
    WA("wa", "Walloon", ""),
    WO("wo", "Wolof", "Wolof"),
    XH("xh", "Xhosa", ""),
    YI("yi", "Yiddish", ""),
    ZA("za", "Zhuang", ""),
    ZU("zu", "Zulu", "isiZulu"),
    AB("ab", "Abkhazian", ""),
    ZH("zh", "Mandarin", "普通话"),
    PS("ps", "Pushto", "پښتو"),
    AM("am", "Amharic", ""),
    AR("ar", "Arabic", "العربية"),
    BG("bg", "Bulgarian", "български език"),
    CN("cn", "Cantonese", "广州话 / 廣州話"),
    MK("mk", "Macedonian", ""),
    EL("el", "Greek", "ελληνικά"),
    FA("fa", "Persian", "فارسی"),
    HE("he", "Hebrew", "עִבְרִית"),
    HI("hi", "Hindi", "हिन्दी"),
    HY("hy", "Armenian", ""),
    EN("en", "English", "English"),
    EE("ee", "Ewe", "Èʋegbe"),
    KA("ka", "Georgian", "ქართული"),
    PA("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    BN("bn", "Bengali", "বাংলা"),
    BS("bs", "Bosnian", "Bosanski"),
    CH("ch", "Chamorro", "Finu' Chamorro"),
    BE("be", "Belarusian", "беларуская мова"),
    YO("yo", "Yoruba", "Èdè Yorùbá");

    private final String value;
    private final String englishName;
    private final String nativeName;

    OriginLanguageEnum(String value, String englishName, String nativeName) {
        this.value = value;
        this.englishName = englishName;
        this.nativeName = nativeName;
    }

}