### ADMIN 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "admin1",
  "password": "Test123!",
  "email" : "dmarb0313@gmail.com",
  "adminPassword": "1234"
}

### ADMIN 회원가입시 토큰값이 다를 때 실패
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "admin2",
  "password": "Test123!",
  "email" : "dmarb0313@gmail.com",
  "adminPassword": "12341"
}

### USER 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "user1",
  "password": "Test123!",
  "email" : "dmsrb0125@naver.com"
}

### EMAIL 인증
POST http://localhost:8080/email/verify
Content-Type: application/json

{
   "code" : "208263"
}

### ADMIN 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username" : "manager1",
  "password": "Test123!"
}

> {% client.global.set("ADMIN_TOKEN", response.headers.valueOf("Authorization")); %}

### USER 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username" : "user1",
  "password": "Test123!"
}

> {% client.global.set("USER_TOKEN", response.headers.valueOf("Authorization"));
  client.global.set("USER_REFRESH_TOKEN", response.headers.valueOf("REFRESH_TOKEN_HEADER")); %}

### USER 로그아웃
PUT http://localhost:8080/users/logout
Authorization:{{USER_TOKEN}}


### USER 회원탈퇴
DELETE http://localhost:8080/users/signout
Content-Type: application/json
Authorization:{{USER_TOKEN}}


### User Token 재발급
GET http://localhost:8080/users/refresh
Content-Type: application/json
Authorization:{{USER_TOKEN}}
REFRESH_TOKEN_HEADER:{{USER_REFRESH_TOKEN}}

> {% client.global.set("USER_TOKEN",response.headers.valueOf("Authorization"));
  client.global.set("USER_REFRESH_TOKEN",response.headers.valueOf("REFRESH_TOKEN_HEADER")); %}


### User Profile 조회
GET http://localhost:8080/users/profile
Content-Type: application/json
Authorization:{{USER_TOKEN}}

### User Profile 수정
PUT http://localhost:8080/users/profile
Content-Type: application/json
Authorization:{{USER_TOKEN}}

{
  "email" : "user1@gmail.com",
  "name": "열자안넘는이름입니다"
}

### User Password 수정
PUT http://localhost:8080/users/password
Content-Type: application/json
Authorization:{{USER_TOKEN}}

{
  "password": "sparta12!@!"
}