INSERT INTO film_fly.genre (id, genre_id, name) VALUES (1, 28, 'Action');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (2, 12, 'Adventure');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (3, 16, 'Animation');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (4, 35, 'Comedy');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (5, 80, 'Crime');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (6, 99, 'Documentary');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (7, 18, 'Drama');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (8, 10751, 'Family');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (9, 14, 'Fantasy');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (10, 36, 'History');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (11, 27, 'Horror');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (12, 10402, 'Music');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (13, 9648, 'Mystery');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (14, 10749, 'Romance');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (15, 878, 'Science Fiction');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (16, 10770, 'TV Movie');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (17, 53, 'Thriller');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (18, 10752, 'War');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (19, 37, 'Western');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (20, 28, '액션');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (21, 12, '모험');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (22, 16, '애니메이션');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (23, 35, '코미디');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (24, 80, '범죄');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (25, 99, '다큐멘터리');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (26, 18, '드라마');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (27, 10751, '가족');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (28, 14, '판타지');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (29, 36, '역사');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (30, 27, '공포');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (31, 10402, '음악');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (32, 9648, '미스터리');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (33, 10749, '로맨스');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (34, 878, 'SF');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (35, 10770, 'TV 영화');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (36, 53, '스릴러');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (37, 10752, '전쟁');
INSERT INTO film_fly.genre (id, genre_id, name) VALUES (38, 37, '서부');