### ADMIN 회원가입
POST https://localhost/users/signup
Content-Type: application/json

{
  "username": "admin1",
  "password": "Admin1!",
  "email" : "dmarb0313@gmail.com",
  "adminPassword": "1234"
}

### ADMIN 로그인
POST https://localhost/users/login
Content-Type: application/json

{
  "username": "admin5",
  "password": "Admin12345!"
}

### 영화 PK 값
@movieId = 238

### 리뷰 등록
POST https://localhost/movies/{{movieId}}/reviews
Content-Type: application/json

{
  "title": "리뷰 제목22",
  "content": "리뷰 내용22",
  "rating": 4.2
}

### 리뷰 단일 조회
GET https://localhost/reviews/1

### 특정 영화에 대한 리뷰 전체 조회
GET https://localhost/movies/{{movieId}}/reviews

### 리뷰 수정
PATCH https://localhost/reviews/1
Content-Type: application/json

{
  "title": "제목ㅋㅋㅋ",
  "content": "내용ㅋㅋㅋ",
  "rating": 2.1
}

### 리뷰 삭제
DELETE https://localhost/reviews/17