### ADMIN 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "admin1",
  "password": "Test12345!",
  "email" : "dmarb0313@gmail.com",
  "adminPassword": "1234"
}

### ADMIN 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "Test12345!"
}

### 영화 PK 값
@movieId = 238

### 리뷰 등록
POST http://localhost:8080/movies/{{movieId}}/reviews
Content-Type: application/json

{
  "title": "리뷰 제목22",
  "content": "리뷰 내용22",
  "rating": 4.2
}

### 리뷰 단일 조회
GET http://localhost:8080/reviews/20

### 특정 영화에 대한 리뷰 전체 조회
GET http://localhost:8080/movies/{{movieId}}/reviews

### 리뷰 수정
PATCH http://localhost:8080/reviews/1
Content-Type: application/json

{
  "title": "제목ㅋㅋㅋ",
  "content": "내용ㅋㅋㅋ",
  "rating": 2.1
}

### 리뷰 삭제
DELETE http://localhost:8080/reviews/17