### 테스트에 사용할 데이터
@username1 = admin5
@password1 = Admin12345!

### USER 로그인
POST https://localhost/users/login
Content-Type: application/json

{
  "username" : "{{username1}}",
  "password": "{{password1}}"
}

### 댓글 생성
POST https://localhost/boards/28/comments
Content-Type: application/json

{
  "content": "댓글 내용11"
}

### 댓글 단일 조회
GET https://localhost/comments/1

# https://localhost/boards/1/comments?page=1&size=10
### 댓글 페이징 조회
GET https://localhost/boards/1/comments?page=1

### 댓글 수정
PATCH https://localhost/comments/1
Content-Type: application/json

{
  "content": "댓글 내용 수정12345"
}

### 댓글 삭제
DELETE https://localhost/comments/1


### 특정 사용자의 댓글 조회
GET https://localhost/comments/users/7